"""
Create a program that will play the 'cows and bulls' game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that
the user guessed correctly in the correct place, they have a 'cow'. For every digit the user guessed correctly in
the wrong place is a 'bull'. Every time the user makes a guess, tell them how many 'cows' and 'bulls' they have.
Once the user guesses the correct number, the game is over. Keep track of the number of guesses
the user makes throughout the game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
    1234
  2 cows, 0 bulls
    1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""


def generate_number(digits):
    import random
    lista = map(int, random.sample(range(10), digits))
    return lista


def get_cows(guess_num_list, generated_num_list):
    # return len(list(set(generated_num_list).intersection(set(guess_num_list))))
    print list(set(generated_num_list).intersection(set(guess_num_list)))


def get_bulls(guess_num_list, generated_num_list):
    return len(list(set(generated_num_list).difference(set(guess_num_list))))


def get_guess_number():
    return raw_input("Write a number: ")


if __name__ == '__main__':
    print("cows and bulls")
    guess = get_guess_number()
    lista = generate_number(4)
    print lista
    print guess
    print "cows: {}".format(get_cows(list(guess), lista))
    print "bulls: {}".format(get_bulls(list(guess), lista))
